import type { Metadata } from "next";
import "./globals.css";
import { Golos_Text } from "next/font/google"
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const golos_Text = Golos_Text({ weight: ['400', '500', '600', '700', '800', '900'], subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${golos_Text.className} antialiased`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
