import type { Metadata } from "next";
import "./globals.css";
import { Golos_Text } from "next/font/google"
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { AppProvider } from "../Context/AppContext";
import Toggle from "@/components/Toggle";
import React from "react";
import notFound from "@/components/notFound";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from 'next-intl';

const golos_Text = Golos_Text({ weight: ['400', '500', '600', '700', '800', '900'], subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { params } = props;
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${golos_Text.className} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AppProvider>
            <NavBar />
            <Toggle />
            {props.children}
            <Footer />
          </AppProvider>
        </NextIntlClientProvider>

      </body>
    </html>

  );
}
